### ISSUE TITLE
Add Travis CI build status into README

### ISSUE THREAD

**Issue by VoyTechnology** [VoyTechnology/CPSSDChat#12]
Would be a nice addition to see how well the project is going

**Comment by GoldenBadger** [comment]
While you're at it, mention that to run the backend run `go run main.go` from the repo root.

**Comment by VoyTechnology** [comment]
oh yea. Solved in 70e1086

**Comment by GoldenBadger** [comment]
Another thing you can do in your pull request or even commit message is say "Closes #12" and it will automatically close the issue when merged into your default branch.

**Comment by VoyTechnology** [comment]
I know I can. I forgot :)
