### ISSUE TITLE
Move development to a real OS

### ISSUE THREAD

**Issue by GoldenBadger** [VoyTechnology/CPSSDChat#7]
I believe that developing CPSSDChat on an OSX clone is negatively impacting the project. Move to a real Linux distro like Arch, and I think you'll see a massive improvement in the project. For more info see [here](https://www.reddit.com/r/archlinuxcirclejerk).

**Comment by VoyTechnology** [comment]
In functionality it is just Ubuntu, so I don't see how it is negatively impacting the project (apart from delays..), its just the look that is different

**Comment by GoldenBadger** [comment]
Actually, that's not true. Everybody knows that the window manager you use dictates the quality of your code. That's why all the best programmers use top-tier WMs like [this](http://www.fvwm.org/screenshots/desktops/GlenLeeEdwards-desk4-1024x768/screenshot.gif).
